### ISSUE TITLE
"SQL logic error: near "COPY": syntax error (1)" when postgres is not active

### ISSUE THREAD

**Issue by evgenybf** [malvere/GoSberScrape#1]
```
$ bin/sber-scrape -mode web  -search велостанок
2023/12/22 23:53:15 Searching for:  велостанок
2023/12/22 23:53:15 Could not ping 'postgres' driver
2023/12/22 23:53:15 Driver 'sqlite' is active
2023/12/22 23:53:15 https://megamarket.ru/catalog/page-1/?q=%D0%B2%D0%B5%D0%BB%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%BA
** extra
2023/12/22 23:53:15 Statement: {} COPY "product_data" ("title", "price", "bonuses", "bonus_percent", "discount", "product_id", "link") FROM STDIN
**
2023/12/22 23:53:15 SQL logic error: near "COPY": syntax error (1)
```

**Comment by mriddi** [comment]
там похоже ошибка появляется когда он ничего не находит и пытается это добавить в базу, а не находит тк не тот ответ от мегамаркета прилетает

**Comment by evgenybf** [comment]
C PostgreSQL не падает, но в итоге пришлось отказаться от ручных запросов и управлять браузером чтобы пройти капчу
https://github.com/malvere/GoSber/issues/2
Где-то раз в 2-3 тысячи запросов они повторяют проверку на бота.

**Comment by malvere** [comment]
Ошибка возникала из-за использования pq.Copy который работает в PostgreSQL в пакете где используется SQLite (litestore), который оператор COPY не поддерживает , при отсутствии позиций пока что будет выдавать ошибку sql.ErrNoRows, расширенную обработку ситуации где отсутствует товар (капча или нет наличия) добавлю в следующих комитах
